### ISSUE TITLE
Проблема с позиционированием комментов

### ISSUE THREAD

**Issue by Hibin** [azeyka/HJ-30_diplom#2]
Нажимаю в середине картинки, а форма появляется где-то сильно левее.

**Comment by azeyka** [comment]
![комментарии](https://user-images.githubusercontent.com/42053726/55463992-bebb3380-562c-11e9-8d32-0c7d44cc97aa.gif) На двух компьютерах проверила - хвостик значка в месте клика. Должно быть по-другому?

**Comment by Hibin** [comment]
Сейчас все хорошо.
